Repository AY2425S1-CS2103T-W09-1/tp, pull requests merged in 2024-10, with the labels that each got.

#68 Add "view" command and relevant tests
  src/main/java/seedu/address/logic/commands/ViewStatusCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewStatusCommandParser.java
  src/test/java/seedu/address/logic/commands/ViewStatusCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewStatusCommandParserTest.java
Labels: type.Task, priority.High

#74 Check for status matches and display to user
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ViewStatusCommand.java
  src/main/java/seedu/address/logic/parser/ViewStatusCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/ViewStatusCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#78 Mark status
  docs/DevOps.md
  docs/Documentation.md
  docs/Logging.md
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/HireCommand.java
  src/main/java/seedu/address/logic/commands/RejectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/HireCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RejectCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Job.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/HireCommandTest.java
  src/test/java/seedu/address/logic/commands/RejectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HireCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RejectCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Epic

#90 Update User Guide to include new features
  docs/UserGuide.md
Labels: priority.Medium

#96 Refine user guide
  docs/UserGuide.md
Labels: type.Task

#97 Improve UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement

#112 Update UML Diagram
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Enhancement

#110 Add a display panel beside personListPanel
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewStatusCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ViewPersonPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/viewPersonPanel.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: type.Enhancement, priority.Medium

#111 Fix hire/reject command displays name in upper case
  src/main/java/seedu/address/logic/commands/HireCommand.java
  src/main/java/seedu/address/logic/commands/RejectCommand.java
Labels: type.Bug

#117 Fix bug hire and reject commands don't update status immediately
  src/main/java/seedu/address/logic/commands/HireCommand.java
  src/main/java/seedu/address/logic/commands/RejectCommand.java
  src/test/java/seedu/address/logic/commands/HireCommandTest.java
  src/test/java/seedu/address/logic/commands/RejectCommandTest.java
Labels: type.Bug

#113 Add a class diagram for HireCommand
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/add-remark/HireCommand.puml
Labels: type.Enhancement, priority.Low

#131 Add SortCommand
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/InterviewScore.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Epic, priority.High
