Repository AY2425S1-CS2103T-W09-1/tp, pull requests merged in 2024-11, with the labels that each got.

#144 Update UG with images and allow Edit Command to show details in Display Panel
  docs/UserGuide.md
  docs/images/Display-Panel.png
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, priority.High

#161 Fix definition of duplicate persons
  src/main/java/seedu/hiredfiredpro/model/person/Job.java
  src/main/java/seedu/hiredfiredpro/model/person/Name.java
  src/main/java/seedu/hiredfiredpro/model/person/Person.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/hiredfiredpro/logic/commands/CommandTestUtil.java
  src/test/java/seedu/hiredfiredpro/model/person/JobTest.java
  src/test/java/seedu/hiredfiredpro/model/person/NameTest.java
  src/test/java/seedu/hiredfiredpro/model/person/PersonTest.java
Labels: alpha-bug

#162 Add tags in display panel
  src/main/java/seedu/hiredfiredpro/ui/ViewPersonPanel.java
  src/main/resources/view/viewPersonPanel.fxml
Labels: priority.Low

#171 Edit user stories and add use cases
  docs/DeveloperGuide.md
  docs/images/UI-Layout.png
Labels: priority.High

#173 Fix empty edit tag changing edited person to pending
  src/main/java/seedu/hiredfiredpro/logic/commands/EditCommand.java
  src/test/java/seedu/hiredfiredpro/logic/commands/EditCommandTest.java
Labels: alpha-bug

#177 Update DG appendix
  docs/DeveloperGuide.md
Labels: priority.High

#227 Fix ViewPersonPanel not showing
  src/main/resources/view/ViewPersonPanel.fxml
Labels: type.Bug, priority.High

#229 Add more extensions
  docs/DeveloperGuide.md
  docs/images/UI-Layout.png
Labels: type.Bug, severity.Low

#231 Update DG
  docs/DeveloperGuide.md
Labels: type.Bug

#228 Update SortCommand
  src/main/java/seedu/hiredfiredpro/model/Model.java
  src/main/java/seedu/hiredfiredpro/model/ModelManager.java
  src/test/java/seedu/hiredfiredpro/logic/commands/AddCommandTest.java
Labels: type.Bug

#230 Update UG after PED
  docs/UserGuide.md
Labels: type.Bug

#237 Fix minor errors
  docs/DeveloperGuide.md
Labels: priority.High
